### ISSUE TITLE
Transfer this project to new organization.

### ISSUE THREAD

**Issue by jmjoy** [graphicsmagick-rs/graphicsmagick-rs#23]
Sometimes I don't have free time to deal with issue and pr, so transfer the project to a separate organization is a good idea.

@NobodyXu and I will be the member.

OK?

**Comment by NobodyXu** [comment]
Thanks @jmjoy 
I'm willing to take time to maintain this project.

**Comment by jmjoy** [comment]
So, what's the better name of the organization?

Also `graphicsmagick-rs`?

**Comment by NobodyXu** [comment]
`graphicsmagick-rs` looks good to me.

**Comment by jmjoy** [comment]
@NobodyXu  What's your `crates.io` ID? I will add you as owner.

**Comment by NobodyXu** [comment]
It's same as my github ID, NobodyXu

**Comment by jmjoy** [comment]
@NobodyXu I have invited you as org member.

**Comment by NobodyXu** [comment]
Thanks, I've received the invitation.
