### ISSUE TITLE
I want to add a function to add a translucent watermark, but I can't find a way without destroying the encapsulation.

### ISSUE THREAD

**Issue by jmjoy** [graphicsmagick-rs/graphicsmagick-rs#42]
> Ref: https://www.jianshu.com/p/3a4cb48fcf90

In this article, we need to hardcode struct `_MagickWand` to get the image pointer.

**Comment by NobodyXu** [comment]
That's unfortunate, perhaps we should open an issue in upstream?

**Comment by jmjoy** [comment]
> That's unfortunate, perhaps we should open an issue in upstream?

Alright.
